### ISSUE TITLE
build.sh not using user-defined .nvmrc node version

### ISSUE THREAD

**Issue by kynetiv** [18F/federalist-docker-build#49]
Hi, I'm noticing in our Federalist builds that our `.nvmrc` version setting is not being used and the `build.sh` is building the current latest (node 8 & npm 5.0.0). Unless I'm mistaken what the purpose of [these lines](https://github.com/18F/federalist-docker-build/blob/staging/build.sh#L37-L40) are, you might need to make them 
```sh
nvm install "$(cat .nvmrc)"
nvm use "$(cat .nvmrc)"
```
similar to how your RVM version is installed.

**Comment by jseppi** [comment]
(Already discussed this in slack, but posting here for posterity as well)

Use of the "stable" version is actually deprecated by nvm, and is just an alias to "node", which installs the latest version, which is 8.0.0 now. Ref: https://github.com/creationix/nvm#usage.

Best to specify an actual version number in your project's `.nvmrc`.

**Comment by kynetiv** [comment]
well, `stable` doesn't point to 8 now, but when I put a value in `.nvmrc` (6.9.2), I'm still seeing node v8.0.0. Perhaps the node PATH is not finding the .nvmrc ?

**Comment by kynetiv** [comment]
Thanks for the help her! `.nvmrc` is working correctly and it turns out the `stable` nvm version was ultimately the problem (now that it points to latest).
