### ISSUE TITLE
Redirect for root URL does not respect BASEURL 

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docker-build#53]
Possibly here: https://github.com/18F/federalist-docker-build/blob/staging/publish.rb#L119

**Comment by jmhooper** [comment]
Discovered this issue while pairing with @jseppi. It looks like the root url for a site will redirect to `/`, even if there is a baseurl present. That appears to be the result of this code: https://github.com/18F/federalist-docker-build/blob/staging/publish.rb#L117-L123

**Comment by jmhooper** [comment]
Also note that this bug was introduced by https://github.com/18F/federalist-docker-build/pull/47 and is only present on staging
